# Generated by Django 4.1.3 on 2022-11-15 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0005_alter_measurement_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='id_sensor',
            new_name='sensor',
        ),
    ]
