# Generated by Django 4.1.3 on 2022-11-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0008_alter_measurement_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='temp',
            field=models.FloatField(),
        ),
    ]
